export const StringConstants = {
  NAME_REQ: 'Name is required!',
  NAME_VAL: 'Name is not valid!',
  F_NAME_REQ: 'First name is required',
  F_NAME_VAL: 'First name is not valid',
  L_NAME_REQ: 'Last name is required',
  L_NAME_VAL: 'Last name is not valid',
  EMAIL_REQ: 'Email is required!',
  EMAIL_VAL: 'Email is not valid!',
  PASS_REQ: 'Password is required!',
  PASS_VAL: 'Special characters are not allowed!',
  PASS_LENGTH: 'Password should be minimum 8 characters',
  Date_REQ: 'Date is required!',
  Date_VAL: 'Date is not valid!',
  NI_REQ: 'National insurance number is required!',
  NI_VAL: 'National insurance number is not valid!',
  UTR_REQ: 'UTR number is required!',
  UTR_VAL: 'UTR number should be exactly 10 digits long!',
  ADD_REQ: 'Address is required!',
  CITY_REQ: 'City is required!',
  PHONE_REQ: 'Phone is required!',
  POST_REQ: 'Postcode is required!',
  POST_VAL: 'Postcode is not valid!',
  COUNTRY_REQ: 'Country is required!',
  DATE_REQ: 'Date is required!',
  DATE_VAL: 'Date is not valid!',
  MARITAL_STATUS_REQ: 'Marital status is required',
  INVALID_PASSWORD: 'Password Not Correct!',
  INVALID_EMAIL: 'Email Does Not Exists in System!',
  RESET_PASSWORD_EMAIL: 'An email has been sent on your provided email with reset password link.',
  RESET_PASSWORD_LIMIT: 'Reset password limit exceeded.!',
};
